# This project is supported by Sstudios Dev, 
# a leading company in this field. Its sponsorship demonstrates a commitment to excellence and innovation. 
# Your support allows us to advance our mission of providing quality products and services to our viewers.

ko_fi: sstudiosdevelopment
patreon: sstudiosdevelopment
custom: ["https://paypal.me/sstudiosDev"]
